### PR TITLE
Create initial version of the page

### PR DESCRIPTION
**Pull request by zaynet**

### CODE REVIEW

**Comment by PatrickJS-kunaico** [comment]
looks great. can you make sure the cards can resize a bit and reorder based on tailwind breakpoints

**Review by PatrickJS-kunaico — APPROVED** [review]

**Comment by PatrickJS-kunaico** [comment]
Screenshot 2023-12-11 at 4 06 25 PM

make sure it's fairly responsive. Remove padding/margins if needed with tailwind sm/md

**Comment by zaynet** [comment]
One thing left - the footer image. I wasn't able to export it correctly. I will fix it once I have several images for different screen sizes.

**Comment by zaynet** [comment]
I have added a similar image that was found on the internet. Will change it once I have the correct one.

image

**Pull request merged**
